apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  labels:
    app: kuard
    run: kuard
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      run: kuard
  template:
    metadata:
      labels:
        run: kuard
    spec:
      containers:
      - name: kuard
        # Image originale (gcr.io/kuar-demo/kuard-amd64:blue) remplacée par nginx
        # Cause : Erreur 403 Forbidden sur le registre Google Container Registry
        image: nginx
        ports:
        # Port adapté pour Nginx (80 au lieu de 8080)
        - containerPort: 80